// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Travel.Data;

#nullable disable

namespace Travel.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250731032955_RemoveUnusedSelectors")]
    partial class RemoveUnusedSelectors
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Travel.Models.CrawlConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BackendApi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("HasLoadMore")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LoadMoreButtonSelector")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MaxLoadMore")
                        .HasColumnType("int");

                    b.Property<string>("SourceAvatarQueryParams")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SourceBaseUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SourceContainer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SourceDurationQueryParams")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SourceEachItemContainer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SourceLinkQueryParams")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SourceName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SourcePriceOriginalQueryParams")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SourcePricePromotionQueryParams")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SourceRatingCountQueryParams")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SourceRatingScoreQueryParams")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SourceSapoQueryParams")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SourceTitleQueryParams")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("CrawlConfigs");
                });

            modelBuilder.Entity("Travel.Models.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EarlyPromotion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GiftPromotion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HighlightReview")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PriceOriginal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PricePromotion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("RatingCount")
                        .HasColumnType("int");

                    b.Property<double?>("RatingScore")
                        .HasColumnType("double");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SlugUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Tours");
                });
#pragma warning restore 612, 618
        }
    }
}
